#!/bin/sh

if test $# -ne 1
then
  echo "Usage: install-civs <settings-file>"
  exit 1
fi

. $1 || exit 1

echo "Read settings file"

    for f in civs_create.html index.html public_elections.html proportional.html sec_priv.html style.css
    do
	echo "copying $f to $HTMLDIR/$f"
	sed  -e 's|@PERL@|'$PERL'|' \
	     -e 's|@CGIBINDIR@|'$CGIBINDIR'|'\
	     -e 's|@THISHOST@|'$THISHOST'|' \
	     -e 's|@CIVSDATADIR@|'$CIVSDATADIR'|' \
	     -e 's|@CIVSBINURL@|'$CIVSBINURL'|' \
	     -e 's|@CIVSURL@|'$CIVSURL'|' \
	     -e 's|@SUPERVISOR@|'$SUPERVISOR'|' \
	     -e 's|@SMTPHOST@|'$SMTPHOST'|' \
	< $f > "${HTMLDIR}/$f"
    done

    for f in add_voters beatpath.pm civs_common.pm close control \
	create_election election.pm mail.pm results \
	start_election vote
    do
	echo "copying cgi-bin/$f"
	sed  -e 's|@PERL@|'$PERL'|' \
	     -e 's|@CGIBINDIR@|'$CGIBINDIR'|'\
	     -e 's|@THISHOST@|'$THISHOST'|' \
	     -e 's|@CIVSDATADIR@|'$CIVSDATADIR'|' \
	     -e 's|@CIVSBINURL@|'$CIVSBINURL'|' \
	     -e 's|@CIVSURL@|'$CIVSURL'|' \
	     -e 's|@SUPERVISOR@|'$SUPERVISOR'|' \
	     -e 's|@SMTPHOST@|'$SMTPHOST'|' \
	< "cgi-bin/$f" > "$CGIBINDIR/$f"
    done
