#!/bin/bash

TestAndCreateDir() {
    # echo "Checking for directory $1"
    if test ! -d "$1"; then
	echo "Directory $1 does not exist. Creating it.";
        mkdir "$1";
    fi
}

if test $# -ne 1
then
  echo "Usage: install-jcivs <settings-file>";
  exit 1;
fi

. $1 || exit 1

echo "Read settings file $1."

TestAndCreateDir "$SERVLET_DIR";
TestAndCreateDir "$HTML_DIR";
TestAndCreateDir "$CIVS_DATA_DIR";
TestAndCreateDir "$CIVS_DATA_DIR/elections";

echo "Servlet directory is $SERVLET_DIR"
echo "HTML directory is $HTML_DIR"
echo "CIVS data directory is $CIVS_DATA_DIR"

CIVS_DATA_DIR=`echo $CIVS_DATA_DIR | sed -e 's@\\\\@\\\\\\\\@g' \
                                     -e 's@ @\\\\ @g'` || exit 1

Subst() {
    base="`basename $1`"
    sed  < "$1" \
	 > "$2/$base" \
	    -e 's|@HTML_DIR@|'"$HTML_DIR"'|'\
	    -e 's|@CIVS_DATA_DIR@|'"$CIVS_DATA_DIR"'|' \
	    -e 's|@CIVSBINURL@|'"$CIVSBINURL"'|' \
	    -e 's|@CIVSURL@|'"$CIVSURL"'|' \
	    -e 's|@SUPERVISOR@|'"$SUPERVISOR"'|' \
	    -e 's|@SMTPHOST@|'"$SMTPHOST"'|' \
	    -e 's|@LOCALDEBUG@|'"$LOCALDEBUG"'|' \
	    -e 's|@ADDTOPATH@|'"$ADDTOPATH"'|' \
	    -e 's|@SERVLET_URL@|'"$SERVLET_URL"'|' \
	    -e 's|@CIVS_HOME@|'"$CIVS_HOME"'|' \
	    -e 's|@CIVS_HOME_EXTERNAL@|'"$CIVS_HOME_EXTERNAL"'|' \
	    -e 's|@STYLE_SHEET_URL@|'"$STYLE_SHEET_URL"'|'
}

for f in html/*.html html/*.css html/*.js
do
    Subst $f "$HTML_DIR"
done

webinf="$SERVLET_DIR/WEB-INF"
TestAndCreateDir "$webinf"
classes="$webinf/classes"
TestAndCreateDir "$classes"

Subst web.xml "$webinf"
cp -r classes/civs "$classes"
cp -r classes/servlet "$classes"

if [ ! -s $CIVS_DATA_DIR/private_host_id ]; then
    echo "*********************************************";
    echo "                 WARNING                     ";
    echo "*********************************************";
    echo "";
    echo "No private key exists for the server!";
    echo "";
    echo "Creating a private key using the openssl pseudo-random number";
    echo "generator.  If you want more randomness than this, you will";
    echo "need to create your own key.  See the INSTALL file for more";
    echo "information."
    echo "";
    openssl rand -base64 32 -out $CIVS_DATA_DIR/private_host_id;
    echo "*********************************************";
fi

if [ ! -s $CIVS_DATA_DIR/nonce_seed ]; then
    echo "Seeding the CIVS nonce generator.";
    openssl rand -base64 32 -out $CIVS_DATA_DIR/nonce_seed;
fi

touch $CIVS_DATA_DIR/nonce_seed $CIVS_DATA_DIR/log
chmod ugo+w $CIVS_DATA_DIR/nonce_seed $CIVS_DATA_DIR/log
	
echo "Install completed.  Check for any errors reported above.";
